apiVersion: v1
kind: Pod
metadata:
  name: kuard-podv2
  labels:
    app: kuard-podv2
spec:
  containers:
  - image: gcr.io/kuar-demo/kuard-amd64:1
    name: kuard
    ports:
    - containerPort: 8080
      protocol: TCP
      name: http
    resources:
      requests:
        cpu: 100m
        memory: 100Mi 
      limits:
        cpu: 500Mi
        memory: 500Mi


