apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: ReplicaSet
metadata:
  name: wordpress
  labels:
    app: wordpress-pod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress-pod
  template:
    metadata:
      labels:
        app: wordpress-pod
    spec:
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/www/html
